create database credits;

use credits;

CREATE TABLE IF NOT EXISTS CLIENTES(
	CUSTOMERID INTEGER NOT NULL PRIMARY KEY, 
    NOMBRE VARCHAR(35) NOT NULL,
    APELLIDOS VARCHAR(35) NOT NULL,
    F_NACIMIENTO DATE NOT NULL,
    EDAD SMALLINT,
    CALLE_Y_NUMERO VARCHAR(60) NOT NULL,
    CP VARCHAR(5) NOT NULL,
    MUNICIPIO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(4) NOT NULL,
    TELEFONO VARCHAR(10)
    );
    
CREATE TABLE IF NOT EXISTS PRESTAMOS(
	CONTRACTID INTEGER NOT NULL,
    CUSTOMERID INTEGER NOT NULL,
    FECHA_INI DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    MONTO_TOTAL DECIMAL(8,2) NOT NULL,
    FREQ_PAGOS SMALLINT NOT NULL,
    MONTO_PAGOS DECIMAL(8,2)
	);

CREATE TABLE IF NOT EXISTS PAGOS(
	PAYMENTID INTEGER NOT NULL,
    CONTRACTID INTEGER,
    CUSTOMERID INTEGER,
    FECHA_LIM DATE NOT NULL,
    MONTO_ADEUDO DECIMAL(8,2) NOT NULL,
    MONTO_PAGO DECIMAL(8,2) NOT NULL,
    FECHA_PAGO DATE NOT NULL
	);
    

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CUSTOMERID) REFERENCES CLIENTES(CUSTOMERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRESTAMOS ADD CONSTRAINT PK_CLIENTE_P PRIMARY KEY (CONTRACTID, CUSTOMERID);

ALTER TABLE PAGOS ADD CONSTRAINT FK_PRESTAMOS FOREIGN KEY (CONTRACTID, CUSTOMERID) REFERENCES PRESTAMOS(CONTRACTID, CUSTOMERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PAGOS ADD CONSTRAINT PK_PAGOS PRIMARY KEY (PAYMENTID);





