use credits;

-- Select all customers that have multiple active loans
SELECT c.CUSTOMERID, c.NOMBRE ,c.APELLIDOS, COUNT(*) as ACTIVE_LOANS
from CLIENTES c join PRESTAMOS p on p.CUSTOMERID =  c.CUSTOMERID 
GROUP BY p.CUSTOMERID
HAVING COUNT(*) > 1 ;

-- Select the total amount paid grouped by zip code and age buckets
SELECT SUM(p.MONTO_PAGO) AS TOTAL_PAGADO, c.CP, c.EDAD
from CLIENTES c join PRESTAMOS o on c.CUSTOMERID = o.CUSTOMERID
join PAGOS p on p.CONTRACTID = o.CONTRACTID
group by c.CP, c.EDAD order by c.CP ASC;


-- Select the total amount paid and the average number of payments made by customers that have only one active loan
CREATE VIEW TOTAL_AVG AS SELECT c.NOMBRE, c.APELLIDOS, c.EDAD, o.CONTRACTID, o.CUSTOMERID, p.MONTO_PAGO, p.FECHA_PAGO,  COUNT(*) AS ACTIVE_LOANS, COUNT(p.PAYMENTID) AS No_DE_PAGOS
 FROM CLIENTES c JOIN PRESTAMOS o ON c.CUSTOMERID = o.CUSTOMERID LEFT JOIN PAGOS p ON o.CONTRACTID = p.CONTRACTID
 group by o.CUSTOMERID HAVING COUNT(*) >= 1;
 
SELECT * FROM TOTAL_AVG;

SELECT SUM(MONTO_PAGO) AS MONTO_TOTAL_PAGADO, AVG(NO_DE_PAGOS) AS PROMEDIO_DE_PAGOS_CON_1_CONTRATO FROM TOTAL_AVG WHERE ACTIVE_LOANS = 1;

-- Select all customers that have made two consecutive payments any of their active loans.
CREATE VIEW LAST_PAYMENTS AS SELECT c.CUSTOMERID, c.NOMBRE, c.APELLIDOS, p.FECHA_PAGO, p.MONTO_PAGO, p.PAYMENTID, p.CONTRACTID
FROM CLIENTES c JOIN PAGOS p ON p.CUSTOMERID = c.CUSTOMERID GROUP BY c.CUSTOMERID, PAYMENTID;

SELECT CUSTOMERID, NOMBRE, APELLIDOS, FECHA_PAGO FROM LAST_PAYMENTS GROUP BY CUSTOMERID, FECHA_PAGO ORDER BY CUSTOMERID, FECHA_PAGO;
